name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  go1_15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: test
        run: go test -v ./...
        
  go1_16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: test
        run: go test -v ./...
